#spring.application.name=service-order
#server.port=8000
#spring.cloud.nacos.server-addr=127.0.0.1:8848
#spring.config.import=nacos:service-order.properties
server:
  port: 8000
spring:
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  config:
    import:
      nacos:service-order.properties
  profiles:
    include: feign, sentinel


logging:
  level:
    com.atguigu.order.feign: debug
